### ISSUE TITLE
Is there a way to upper() a sequence?

### ISSUE THREAD

**Issue by willsharpless** [BjornFJohansson/pydna#53]
I tried to plasmid.seq.upper() but it seems to have broken the class; later on when attempting an assembly that was previously working, I then received the error:

'Seq' object has not attribute 'circular'

![image](https://user-images.githubusercontent.com/52509586/60997059-bf89f280-a30a-11e9-80b7-2f18284765e7.png)

In general, is this the acceptable way to edit the seq? Another case I had was like:

![image](https://user-images.githubusercontent.com/52509586/60997806-8b173600-a30c-11e9-9499-74a49bad88f3.png)

Which seemed to work fine ... unless it is what caused my error.

Thanks for your help Bjorn.

**Comment by willsharpless** [comment]
full error:
![image](https://user-images.githubusercontent.com/52509586/60997866-b4d05d00-a30c-11e9-95a8-c23836edf22b.png)

**Comment by BjornFJohansson** [comment]
Hi, In the first case, what are the types for `plas_sin_pro` and new_pro_with_overlap["SFFV"] ?
The Assembly algorithm expects a list or some other iterable of Dseqrecord objects. This Dseqrecord object needs to contain a Dseq object internally. See [this notebook](https://gist.github.com/BjornFJohansson/009fe741882385a536de3cd73b9a9084)
If you want to `upper`, see the workaround at the end of the notebook. 

This happens since I never implemented upper for the Dseq and Dseqrecord, so the methods from the underlying Seq and SeqRecord are used. 

I do not think I ever changed case for a sequence. Do you think there is a need for upper, it should be easy to implement.

BTW are you using the latest pydna?

**Comment by willsharpless** [comment]
Hi Bjorn.

Both plas_sin_pro and new_pro_with_overlap["SFFV"] are single Dseqrecord objects (the latter being called from a dictionary of Dseqrecords). I will try making a list of the two Dseqrecords and see if it gives me success. I will also try using your work around for upper(). I suspect the issue was the latter because I was having partial success before upper(), but the problem was I digested a backbone from a different plasmid and it made the cases lower so I had to upper() them again in order to do a make-shift infusion cloning method with the assembly system.

I would appreciate a lower and an upper; I understand you have created these systems with intended workflows, but the upper() and lower() would allow for more control over user editing for these non-canonical assembly directions or ideas.

I downloaded pydna last week so I believe its up to date.

Thanks again!

**Comment by willsharpless** [comment]
Worked!

Would definitely appreciate an upper() and lower().

**Comment by BjornFJohansson** [comment]
Ok, I will implement upper and lower for the Dseq and Dseqrecord methods.
I would expect to have this in about two weeks from now.

**Comment by Benedict-Carling** [comment]
Hello @BjornFJohansson  👋 I believe this issue has been solved and can now be closed

```bash
## [3.0.2a1] - 2019-07-23

### Changed

-.upper() and .lower() methods for Dseq and Dseqrecord classes. Improved slicing
```

^ from the change log
